### ISSUE TITLE
Capture the intro / outro slides

### ISSUE THREAD

**Issue by jennybc** [rstats-wtf/wtf-2022-rsc#3]

**Comment by shannonpileggi** [comment]
These are already saved under [materials](https://github.com/rstats-wtf/wtf-2022-rsc/tree/main/materials) and linked on [day1_1](https://rstats-wtf.github.io/wtf-2022-rsc/day1_1) and [day2_4](https://rstats-wtf.github.io/wtf-2022-rsc/day2_4) pages. Did you mean something beyond that?

**Comment by jennybc** [comment]
This was a reminder to me to get access to the underlying slides, which is now done. I.e. I wanted future WTF instructors to have access to what the PDFs are made from.
